version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "3.3.x"
    
  - package-ecosystem: gradle
    directory: "/"
    target-branch: "3.3.x"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    labels:
      - "dependency-upgrade"
    commit-message:
      prefix: "3.3.x"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: gradle
    directory: "/"
    target-branch: "3.2.x"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    labels:
      - "dependency-upgrade"
    commit-message:
      prefix: "3.2.x"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
