version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "3.5.x"

  - package-ecosystem: gradle
    directory: "/"
    target-branch: "3.5.x"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    labels:
      - "dependency-upgrade"
    commit-message:
      prefix: "(3.5.x)"
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.boot:spring-boot-dependencies"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: gradle
    directory: "/"
    target-branch: "3.4.x"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    labels:
      - "dependency-upgrade"
    commit-message:
      prefix: "(3.4.x)"
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.boot:spring-boot-dependencies"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: gradle
    directory: "/"
    target-branch: "3.3.x"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    labels:
      - "dependency-upgrade"
    commit-message:
      prefix: "(3.3.x)"
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.boot:spring-boot-dependencies"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"

  - package-ecosystem: gradle
    directory: "/"
    target-branch: "3.2.x"
    schedule:
      interval: daily
    open-pull-requests-limit: 15
    labels:
      - "dependency-upgrade"
    commit-message:
      prefix: "(3.2.x)"
    ignore:
      - dependency-name: "org.springframework.boot"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
      - dependency-name: "org.springframework.boot:spring-boot-dependencies"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
