image:https://img.shields.io/badge/Revved%20up%20by-Develocity-06A0CE?logo=Gradle&labelColor=02303A["Revved up by Develocity", link="https://ge.spring.io/scans?&search.rootProjectNames=spring-credhub"]

== Spring CredHub

Spring CredHub provides client-side support for storing, retrieving, and deleting credentials from a https://github.com/cloudfoundry-incubator/credhub[CredHub] server running in a https://www.cloudfoundry.org/[Cloud Foundry] platform.

See the https://spring.io/projects/spring-credhub[project site] and https://docs.spring.io/spring-credhub/docs/current/reference/html5/[reference documentation] for more information.

=== Demo Application

A simple application that demonstrates the use of Spring CredHub is available in link:/spring-credhub-demo[this repository].

== Building

=== Basic Compile and Unit Tests

To build the source you will need to install JDK 17.

Spring CredHub uses Gradle for most build-related activities, and you should be able to get off the ground quite quickly by cloning the project you are interested in and typing:

[source,bash]
----
./gradlew build
----

=== Integration Tests

Spring CredHub integration tests need a CredHub server.

Refer to link:credhub-server/README.adoc[credhub-server] for information on how to start it up.

Once running they can be executed with:

[source,bash]
----
./gradlew build -PintegrationTests --no-parallel
----

=== Working with the code

If you don't have an IDE preference we would recommend that you use
https://www.springsource.com/developer/sts[Spring Tools Suite] or
https://eclipse.org[Eclipse] when working with the code. 
