image::https://build.spring.io/plugins/servlet/wittified/build-status/SPRINGCREDHUB-CORE[Build Status,link=https://build.spring.io/browse/SPRINGCREDHUB-CORE]

image::https://spring.io/badges/spring-credhub/snapshot.svg[link=https://projects.spring.io/spring-credhub#quick-start]

= Spring CredHub

Spring CredHub provides client-side support for storing, retrieving, and deleting credentials from a https://github.com/cloudfoundry-incubator/credhub[CredHub] server running in a https://www.cloudfoundry.org/[Cloud Foundry] platform.

See the https://projects.spring.io/spring-credhub/[project site] for more information.

=== Demo Application

A simple application that demonstrates the use of Spring CredHub is available in link:/spring-credhub-demo[this repository].

== Building

=== Basic Compile and Test

To build the source you will need to install JDK 1.6.

Spring CredHub uses Gradle for most build-related activities, and you should be able to get off the ground quite quickly by cloning the project you are interested in and typing

----
$ ./gradlew install
----

=== Working with the code

If you don't have an IDE preference we would recommend that you use
https://www.springsource.com/developer/sts[Spring Tools Suite] or
https://eclipse.org[Eclipse] when working with the code. 
