services:
  uaa:
    image: ${DOCKERHUB_MIRROR_REGISTRY}/pcfseceng/uaa
    volumes:
      - ./uaa.yml:/uaa/uaa.yml
    ports:
      - "8080:8080"
    restart: always

  credhub:
    image: ${DOCKERHUB_MIRROR_REGISTRY}/pcfseceng/credhub
    ports:
      - "9000:9000"
    links:
      - uaa:uaa
    depends_on:
      - uaa
    volumes:
      - ./credhub-v2-certs:/etc/server_certs
    environment:
      UAA_URL: http://uaa:8080/uaa
      TRUST_STORE_PASSWORD: changeme
      KEY_STORE_PASSWORD: changeme
      ENCRYPTION_PASSWORD: changeme

  credhub-v1:
    image: ${DOCKERHUB_MIRROR_REGISTRY}/ampersand8/credhub
    ports:
      - "9001:9000"
    links:
      - uaa:uaa
    depends_on:
      - uaa
    environment:
      UAA_URL: http://localhost:8080/uaa
      UAA_INTERNAL_URL: http://uaa:8080/uaa
