services:
  uaa:
    image: harbor-repo.vmware.com/springcloudservices/spring-credhub-uaa-server
    volumes:
      - ./uaa.yml:/uaa/uaa.yml
    ports:
      - "8080:8080"
    restart: always

  credhub:
    image: harbor-repo.vmware.com/springcloudservices/spring-credhub-credhub-server
    ports:
      - "9000:9000"
    links:
      - uaa:uaa
    depends_on:
      - uaa
    environment:
      UAA_URL: http://localhost:8080/uaa
      UAA_INTERNAL_URL: http://uaa:8080/uaa
