/*
 * Copyright 2016-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.credhub.support.certificate;

import java.util.Objects;

import org.jspecify.annotations.Nullable;

/**
 * A summary of a single version of a certificate, as returned in the {@literal versions}
 * list of a {@link CertificateSummary}. Clients don't typically instantiate objects of
 * this type, but will receive them in response to {@link CertificateSummary} requests.
 *
 * @author Scott Frederick
 */
public class CertificateVersionSummary {

	private final @Nullable String id;

	private final @Nullable String expiryDate;

	private final boolean transitional;

	private final boolean certificateAuthority;

	private final boolean selfSigned;

	private final @Nullable Boolean generated;

	/**
	 * Create a {@link CertificateVersionSummary}.
	 */
	@SuppressWarnings("unused")
	private CertificateVersionSummary() {
		this.id = null;
		this.expiryDate = null;
		this.transitional = false;
		this.certificateAuthority = false;
		this.selfSigned = false;
		this.generated = null;
	}

	/**
	 * Create a {@link CertificateVersionSummary} from the provided parameters. Intended
	 * for internal use. Clients will get {@link CertificateVersionSummary} objects
	 * populated from CredHub responses.
	 * @param id the CredHub-generated ID of this version of the certificate
	 * @param expiryDate the expiration date of this version of the certificate, as an
	 * ISO-8601 string, or an empty string if the server doesn't record one
	 * @param transitional a flag indicating whether this version of the certificate is
	 * currently being used for signing or is being staged
	 * @param certificateAuthority a flag indicating whether this version of the
	 * certificate is itself a certificate authority
	 * @param selfSigned a flag indicating whether this version of the certificate is
	 * self-signed
	 * @param generated a flag indicating whether this version of the certificate was
	 * generated by CredHub, as opposed to being imported
	 */
	public CertificateVersionSummary(String id, String expiryDate, boolean transitional, boolean certificateAuthority,
			boolean selfSigned, @Nullable Boolean generated) {
		this.id = id;
		this.expiryDate = expiryDate;
		this.transitional = transitional;
		this.certificateAuthority = certificateAuthority;
		this.selfSigned = selfSigned;
		this.generated = generated;
	}

	/**
	 * Get the CredHub-generated ID of this version of the certificate.
	 * @return the version ID
	 */
	public @Nullable String getId() {
		return this.id;
	}

	/**
	 * Get the expiration date of this version of the certificate.
	 * @return the expiration date as an ISO-8601 string, or an empty string if the server
	 * doesn't record one
	 * @see <a href=
	 * "https://docs.cloudfoundry.org/api/credhub/version/main/#_get_all_certificates">CredHub
	 * API docs: Get All Certificates</a>
	 */
	public @Nullable String getExpiryDate() {
		return this.expiryDate;
	}

	/**
	 * Get the value of the flag indicating whether this version of the certificate is
	 * currently being used for signing or is being staged.
	 * @return the transitional flag
	 */
	public boolean isTransitional() {
		return this.transitional;
	}

	/**
	 * Get the value of the flag indicating whether this version of the certificate is
	 * itself a certificate authority.
	 * @return the certificate authority flag
	 */
	public boolean isCertificateAuthority() {
		return this.certificateAuthority;
	}

	/**
	 * Get the value of the flag indicating whether this version of the certificate is
	 * self-signed.
	 * @return the self-signed flag
	 */
	public boolean isSelfSigned() {
		return this.selfSigned;
	}

	/**
	 * Get the value of the flag indicating whether this version of the certificate was
	 * generated by CredHub, as opposed to being imported.
	 * @return the generated flag, or {@literal null} if not reported by the server
	 */
	public @Nullable Boolean getGenerated() {
		return this.generated;
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (!(o instanceof CertificateVersionSummary)) {
			return false;
		}
		CertificateVersionSummary that = (CertificateVersionSummary) o;
		return this.transitional == that.transitional && this.certificateAuthority == that.certificateAuthority
				&& this.selfSigned == that.selfSigned && Objects.equals(this.id, that.id)
				&& Objects.equals(this.expiryDate, that.expiryDate) && Objects.equals(this.generated, that.generated);
	}

	@Override
	public int hashCode() {
		return Objects.hash(this.id, this.expiryDate, this.transitional, this.certificateAuthority, this.selfSigned,
				this.generated);
	}

	@Override
	public String toString() {
		return "CertificateVersionSummary{" + "id='" + this.id + '\'' + ", expiryDate='" + this.expiryDate + '\''
				+ ", transitional=" + this.transitional + ", certificateAuthority=" + this.certificateAuthority
				+ ", selfSigned=" + this.selfSigned + ", generated=" + this.generated + '}';
	}

}
