/*
 * Copyright 2016-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.springframework.credhub.support.certificate;

import java.util.Date;

import org.jspecify.annotations.Nullable;

import org.springframework.credhub.support.CredentialDetails;
import org.springframework.credhub.support.CredentialName;
import org.springframework.credhub.support.CredentialType;

/**
 * The details of a certificate credential that has been written to CredHub. This is a
 * specialization of {@link CredentialDetails} that adds certificate-specific fields.
 *
 * Clients don't typically instantiate objects of this type, but will receive them in
 * response to credential operation requests. The {@literal id} and {@literal name} fields
 * can be used in subsequent requests.
 *
 * @author Scott Frederick
 */
public class CertificateCredentialDetails extends CredentialDetails<CertificateCredential> {

	private final boolean transitional;

	private final @Nullable Date expiryDate;

	private final boolean certificateAuthority;

	private final boolean selfSigned;

	private final @Nullable Boolean generated;

	private final boolean durationOverridden;

	private final @Nullable Integer durationUsed;

	private final @Nullable Integer keyLength;

	/**
	 * Create a {@link CertificateCredentialDetails}.
	 */
	@SuppressWarnings("unused")
	private CertificateCredentialDetails() {
		super();
		this.transitional = false;
		this.expiryDate = null;
		this.certificateAuthority = false;
		this.selfSigned = false;
		this.generated = null;
		this.durationOverridden = false;
		this.durationUsed = null;
		this.keyLength = null;
	}

	/**
	 * Create a {@link CertificateCredentialDetails} from the provided parameters.
	 * Intended for internal use. Clients will get {@link CertificateCredentialDetails}
	 * objects populated from CredHub responses.
	 * @param id the CredHub-generated unique ID of the credential
	 * @param name the client-provided name of the credential
	 * @param credentialType the {@link CredentialType} of the credential
	 * @param transitional a flag indicating whether the certificate will be used for
	 * signing
	 * @param value the client-provided value for the credential
	 */
	public CertificateCredentialDetails(String id, CredentialName name, CredentialType credentialType,
			boolean transitional, CertificateCredential value) {
		super(id, name, credentialType, value);
		this.transitional = transitional;
		this.expiryDate = null;
		this.certificateAuthority = false;
		this.selfSigned = false;
		this.generated = null;
		this.durationOverridden = false;
		this.durationUsed = null;
		this.keyLength = null;
	}

	/**
	 * Get the value of the flag indicating whether the certificate is currently being
	 * used for signing or if it is being staged.
	 * @return the transitional flag
	 */
	public boolean isTransitional() {
		return this.transitional;
	}

	/**
	 * Get the expiration date of the certificate.
	 * @return the certificate's expiration date
	 * @see <a href=
	 * "https://docs.cloudfoundry.org/api/credhub/version/main/#_regenerate_a_certificate">CredHub
	 * API docs: Regenerate a Certificate</a>
	 */
	public @Nullable Date getExpiryDate() {
		return this.expiryDate;
	}

	/**
	 * Get the value of the flag indicating whether the certificate is itself a
	 * certificate authority.
	 * @return the certificate authority flag
	 * @see <a href=
	 * "https://docs.cloudfoundry.org/api/credhub/version/main/#_regenerate_a_certificate">CredHub
	 * API docs: Regenerate a Certificate</a>
	 */
	public boolean isCertificateAuthority() {
		return this.certificateAuthority;
	}

	/**
	 * Get the value of the flag indicating whether the certificate is self-signed.
	 * @return the self-signed flag
	 * @see <a href=
	 * "https://docs.cloudfoundry.org/api/credhub/version/main/#_regenerate_a_certificate">CredHub
	 * API docs: Regenerate a Certificate</a>
	 */
	public boolean isSelfSigned() {
		return this.selfSigned;
	}

	/**
	 * Get the value of the flag indicating whether the certificate value was generated by
	 * CredHub, as opposed to being imported.
	 * @return the generated flag, or {@literal null} if not reported by the server
	 * @see <a href=
	 * "https://docs.cloudfoundry.org/api/credhub/version/main/#_regenerate_a_certificate">CredHub
	 * API docs: Regenerate a Certificate</a>
	 */
	public @Nullable Boolean getGenerated() {
		return this.generated;
	}

	/**
	 * Get the value of the flag indicating whether the requested validity duration was
	 * overridden by a server-configured minimum duration. Only populated when a
	 * certificate is regenerated; {@literal false} for every other certificate
	 * operation's response.
	 * @return the duration overridden flag
	 * @see <a href=
	 * "https://docs.cloudfoundry.org/api/credhub/version/main/#_regenerate_a_certificate">CredHub
	 * API docs: Regenerate a Certificate</a>
	 */
	public boolean isDurationOverridden() {
		return this.durationOverridden;
	}

	/**
	 * Get the validity duration in days actually used to regenerate the certificate,
	 * which may differ from the requested duration if it was overridden by a
	 * server-configured minimum. Only populated when a certificate is regenerated;
	 * {@literal null} for every other certificate operation's response.
	 * @return the duration used, or {@literal null} if not reported by the server
	 * @see <a href=
	 * "https://docs.cloudfoundry.org/api/credhub/version/main/#_regenerate_a_certificate">CredHub
	 * API docs: Regenerate a Certificate</a>
	 */
	public @Nullable Integer getDurationUsed() {
		return this.durationUsed;
	}

	/**
	 * Get the length of the certificate's key. Only populated when a certificate is
	 * regenerated; {@literal null} for every other certificate operation's response.
	 * @return the key length, or {@literal null} if not reported by the server
	 * @see <a href=
	 * "https://docs.cloudfoundry.org/api/credhub/version/main/#_regenerate_a_certificate">CredHub
	 * API docs: Regenerate a Certificate</a>
	 */
	public @Nullable Integer getKeyLength() {
		return this.keyLength;
	}

}
