artifactory-server: https://repo.spring.io
build-name: spring-credhub
spring-credhub-slack-success-channel: "#spring-cloud-app-broker"
spring-credhub-slack-failure-channel: "#spring-cloud-app-broker"
