---
aliases:
  - &slack-success-notification
    put: alert
    params:
      icon_emoji: ":concourse:"
      username: concourse
      channel: ((spring-credhub-slack-success-channel))
      text: "$BUILD_PIPELINE_NAME pipeline has succeeded with build <${ATC_EXTERNAL_URL}/builds/$BUILD_ID|$BUILD_NAME>!"
  - &slack-failure-notification
    put: alert
    params:
      icon_emoji: ":animal-1252:"
      username: concourse
      channel: ((spring-credhub-slack-failure-channel))
      text: <!here> Build <${ATC_EXTERNAL_URL}/builds/$BUILD_ID|$BUILD_NAME> of job $BUILD_JOB_NAME in the $BUILD_PIPELINE_NAME pipeline has failed!

jobs:
  - name: build
    serial: true
    public: true
    plan:
      - get: pull-request
        trigger: true
        version: every
      - task: build-project
        timeout: 1h30m
        privileged: true
        tags: [ btrfs ]
        file: pull-request/ci/tasks/build-project.yml
        input_mapping:
          git-repo: pull-request
        vars:
          ci-image-tag: ((ci-image-tag))
    on_success:
      *slack-success-notification
    on_failure:
      *slack-failure-notification

resource_types:
  - name: pull-request
    type: registry-image
    source:
      repository: ((dockerhub-mirror-registry))/teliaoss/github-pr-resource
      tag: latest

  - name: slack-notification
    type: registry-image
    source:
      repository: ((dockerhub-mirror-registry))/cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: pull-request
    type: pull-request
    check_every: 10s
    source:
      repository: ((spring-credhub-pr-github-pull-requests-repo))
      access_token: ((spring-credhub-pr-github-pull-requests-access-token))
      base_branch: ((branch))
      disable_forks: true
      required_review_approvals: 1

  - name: alert
    type: slack-notification
    source:
      url: ((scs-slack-webhook))
