[[boot-configuration]]
== Spring Boot Configuration

When using the Spring CredHub starter dependency, Spring CredHub can be configured with https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html#boot-features-external-config-application-property-files[Spring Boot application properties file].
With the proper configuration, Spring CredHub will auto-configure a connection to a CredHub server.

=== Mutual TLS Authentication

An application running on Cloud Foundry can authenticate to a CredHub server deployed to the same platform using https://github.com/cloudfoundry-incubator/credhub/blob/master/docs/mutual-tls.md[mutual TLS].
Mutual TLS is the default authentication scheme when no other authentication credentials are provided.
To use mutual TLS authentication to a CredHub server, simply provide the URL of the CredHub server as an application property:

[source,properties,%autofit]
----
include::{examples-dir}/config-minimal.yml[]
----

An application running on Cloud Foundry can use the internal address `https://credhub.service.cf.internal:8844` to communicate with a CredHub server deployed to the same platform.

=== OAuth2 Authentication

OAuth2 can be used to authenticate via UAA to any CredHub server via UAA.
Spring CredHub supports client credentials grant tokens for authentication with the following configuration: 

[source,properties,%autofit]
----
include::{examples-dir}/config-oauth2.yml[]
----

The OAuth2 client identified by the `client-id` must have CredHub scopes such as `credhub.read` or `credhub.write` to perform most operations. 


