[[http-clients]]
== HTTP Client Support

Spring CredHub `CredHubOperations` supports multiple HTTP client libraries to communicate with the CredHub API. The following libraries are supported:

* Java’s builtin `HttpURLConnection` (default)
* https://hc.apache.org/[Apache HttpComponents]

Choosing a specific client library requires the appropriate dependency to be available on the application classpath.
The application classpath will be inspected for each client library in the order listed above.

Spring CredHub `ReactiveCredHubOperations` only supports the Netty HTTP client library.

=== Apache HttpComponents

To use Apache HttpComponents to communicate with CredHub, add the following dependency to the application:

[source,xml,%autofit]
----
<dependency>
  <groupId>org.apache.httpcomponents.client5</groupId>
  <artifactId>httpclient5</artifactId>
</dependency>
----

WARNING: Apache HttpClient's https://hc.apache.org/httpcomponents-client-5.5.x/logging.html[wire logging] can be enabled through logging configuration. Make sure to not accidentally enable wire logging as logs may expose traffic (including tokens and secrets) between your application and CredHub in plain text.
