[[http-clients]]
== HTTP Client Support

Spring CredHub `CredHubOperations` supports multiple HTTP client libraries to communicate with the CredHub API. The following libraries are supported:

* Java’s builtin `HttpURLConnection` (default)
* https://hc.apache.org/[Apache HttpComponents]
* http://square.github.io/okhttp/[OkHttp 3]
* https://netty.io/[Netty]

Choosing a specific client library requires the appropriate dependency to be available on the application classpath.
The application classpath will be inspected for each client library in the order listed above.

Spring CredHub `ReactiveCredHubOperations` only supports the Netty HTTP client library.

=== Apache HttpComponents

To use Apache HttpComponents to communicate with CredHub, add the following dependency to the application:

[source,xml,%autofit]
----
<dependency>
  <groupId>org.apache.httpcomponents</groupId>
  <artifactId>httpclient</artifactId>
</dependency>
----

=== OkHttp 3

To use OkHttp 3 to communicate with CredHub, add the following dependency to the application:

[source,xml,%autofit]
----
<dependency>
  <groupId>com.squareup.okhttp3</groupId>
  <artifactId>okhttp</artifactId>
</dependency>
----

=== Netty

To use Netty to communicate with CredHub, add the following dependency to the application:

[source,xml,%autofit]
----
<dependency>
  <groupId>io.netty</groupId>
  <artifactId>netty-all</artifactId>
</dependency>
----
