:apidocs-credentials: {apidocs-home}?org/springframework/credhub/core/credential/CredHubCredentialOperations.html
:apidocs-certificates: {apidocs-home}?org/springframework/credhub/core/certificate/CredHubCertificateOperations.html
:apidocs-permissions: {apidocs-home}?org/springframework/credhub/core/permission/CredHubPermissionOperations.html
:apidocs-permissionsV2: {apidocs-home}?org/springframework/credhub/core/permissionV2/CredHubPermissionV2Operations.html
:apidocs-interpolation: {apidocs-home}?org/springframework/credhub/core/interpolation/CredHubInterpolationOperations.html
:apidocs-info: {apidocs-home}?org/springframework/credhub/core/info/CredHubInfoOperations.html

[[operations]]
== Introduction to CredHubOperations

The interface `org.springframework.credhub.core.CredHubOperations` and the implementation `org.springframework.credhub.core.CredHubTemplate` are the central classes in Spring CredHub.
`CredHubOperations` provides access to additional operations interfaces that model the full CredHub API:

[source,java,%autofit]
----
/**
 * Get the operations for saving, retrieving, and deleting credentials.
 */
CredHubCredentialOperations credentials();

/**
 * Get the operations for adding, retrieving, and deleting credential permissions.
 */
CredHubPermissionOperations permissions();

/**
 * Get the operations for adding, retrieving, and deleting credential permissions.
 */
CredHubPermissionV2Operations permissionsV2();

/**
 * Get the operations for retrieving, regenerating, and updating certificates.
 */
CredHubCertificateOperations certificates();

/**
 * Get the operations for interpolating service binding credentials.
 */
CredHubInterpolationOperations interpolation();

/**
 * Get the operations for retrieving CredHub server information.
 */
CredHubInfoOperations info();
----

=== Mapping to CredHub API

Each method of the `Operations` interfaces maps directly to one endpoint of the CredHub HTTP API.
The following table shows the mapping between the CredHub API and the appropriate Spring CredHub `Operations` interface.

[cols="2"]
|===
| {credhub-api-credentials}[CredHub Credentials API]
| {apidocs-credentials}[CredHubCredentialOperations]

| {credhub-api-permissions}[CredHub Permissions API] (v1)
| {apidocs-permissions}[CredHubPermissionOperations]

| {credhub-api-permissionsV2}[CredHub Permissions API] (v2)
| {apidocs-permissionsV2}[CredHubPermissionV2Operations]

| {credhub-api-certificates}[CredHub Certificates API]
| {apidocs-certificates}[CredHubCertificateOperations]

| {credhub-api-interpolation}[CredHub Interpolation API]
| {apidocs-interpolation}[CredHubInterpolationOperations]

| {credhub-api-info}[CredHub Information API]
| {apidocs-info}[CredHubInfoOperations]
|===

=== CredHubOperations Auto-configuration

A `CredHubOperations` Spring bean is created using Spring Boot auto-configuration when application properties are properly configured.
Application classes can autowire an instance of this bean to interact with a CredHub server.

[source,java,%autofit]
----
include::{examples-dir}CredHubService.java[]
----
